






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace PurePunjabi.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }		

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	    [SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }
	
        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; }       
	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}		

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

		[SitecoreInfo(SitecoreInfoType.TemplateId)]
        public virtual Guid TemplateId { get; private set; }
	}
}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// ICarousel Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Carousel</para>	
	/// <para>ID: 1ecaac6d-0707-4c59-b0f5-53a093d78d08</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselConstants.TemplateIdString, Cachable=false)]
	public partial interface ICarousel : IGlassBase 
	{
			
					/// <summary>
					/// The Image1 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 0430c503-f55c-4662-9325-fe6237eb59bd</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselConstants.Image1FieldName)]
					Image Image1  {get; set;}
			
			
					/// <summary>
					/// The Image2 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 642c8f26-2e5c-47a5-9d8b-6e138d65aa51</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselConstants.Image2FieldName)]
					Image Image2  {get; set;}
			
			
					/// <summary>
					/// The Image3 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 99dc5bfb-96b7-4ad3-b137-1562c66601d5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselConstants.Image3FieldName)]
					Image Image3  {get; set;}
			
			
	}


	public static partial class ICarouselConstants{

			public const string TemplateIdString = "1ecaac6d-0707-4c59-b0f5-53a093d78d08";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Carousel";

		
			
			public static readonly ID Image1FieldId = new ID("0430c503-f55c-4662-9325-fe6237eb59bd");
			public const string Image1FieldName = "Image1";
			
		
			
			public static readonly ID Image2FieldId = new ID("642c8f26-2e5c-47a5-9d8b-6e138d65aa51");
			public const string Image2FieldName = "Image2";
			
		
			
			public static readonly ID Image3FieldId = new ID("99dc5bfb-96b7-4ad3-b137-1562c66601d5");
			public const string Image3FieldName = "Image3";
			
			

	}

	
	/// <summary>
	/// Carousel
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Carousel</para>	
	/// <para>ID: 1ecaac6d-0707-4c59-b0f5-53a093d78d08</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselConstants.TemplateIdString, Cachable=false)] 
	public partial class Carousel  : GlassBase, ICarousel 
	{
	   
		
				/// <summary>
				/// The Image1 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 0430c503-f55c-4662-9325-fe6237eb59bd</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselConstants.Image1FieldName)]
				public virtual Image Image1  {get; set;}
					
		
				/// <summary>
				/// The Image2 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 642c8f26-2e5c-47a5-9d8b-6e138d65aa51</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselConstants.Image2FieldName)]
				public virtual Image Image2  {get; set;}
					
		
				/// <summary>
				/// The Image3 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 99dc5bfb-96b7-4ad3-b137-1562c66601d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselConstants.Image3FieldName)]
				public virtual Image Image3  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IHomePage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/HomePage</para>	
	/// <para>ID: 223ea2d3-e136-4e9a-9f09-90dd06aef73a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomePageConstants.TemplateIdString, Cachable=false)]
	public partial interface IHomePage : IGlassBase 
	{
			
	}


	public static partial class IHomePageConstants{

			public const string TemplateIdString = "223ea2d3-e136-4e9a-9f09-90dd06aef73a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HomePage";

			

	}

	
	/// <summary>
	/// HomePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/HomePage</para>	
	/// <para>ID: 223ea2d3-e136-4e9a-9f09-90dd06aef73a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomePageConstants.TemplateIdString, Cachable=false)] 
	public partial class HomePage  : GlassBase, IHomePage 
	{
	   
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IContactUs Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/ContactUs</para>	
	/// <para>ID: 42cd69ba-6f81-440e-a9f5-d2a4bf115e52</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContactUsConstants.TemplateIdString, Cachable=false)]
	public partial interface IContactUs : IGlassBase , global::PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi.IBase_Page
	{
			
					/// <summary>
					/// The Abstract field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: fdd379b2-7075-40ac-abf1-e54fdb9ae183</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IContactUsConstants.AbstractFieldName)]
					string Abstract  {get; set;}
			
			
					/// <summary>
					/// The Email-Id field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: a10929f6-9134-4690-8dfd-f1707a40dfa9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IContactUsConstants.Email_IdFieldName)]
					Link Email_Id  {get; set;}
			
			
					/// <summary>
					/// The Mobile No field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8ad34cd6-a8bf-487c-add7-fd8931fb442c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IContactUsConstants.Mobile_NoFieldName)]
					string Mobile_No  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a3cf7dc4-6cf5-4861-81cf-1c288d262fa5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IContactUsConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IContactUsConstants{

			public const string TemplateIdString = "42cd69ba-6f81-440e-a9f5-d2a4bf115e52";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "ContactUs";

		
			
			public static readonly ID AbstractFieldId = new ID("fdd379b2-7075-40ac-abf1-e54fdb9ae183");
			public const string AbstractFieldName = "Abstract";
			
		
			
			public static readonly ID Email_IdFieldId = new ID("a10929f6-9134-4690-8dfd-f1707a40dfa9");
			public const string Email_IdFieldName = "Email-Id";
			
		
			
			public static readonly ID Mobile_NoFieldId = new ID("8ad34cd6-a8bf-487c-add7-fd8931fb442c");
			public const string Mobile_NoFieldName = "Mobile No";
			
		
			
			public static readonly ID TitleFieldId = new ID("a3cf7dc4-6cf5-4861-81cf-1c288d262fa5");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// ContactUs
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/ContactUs</para>	
	/// <para>ID: 42cd69ba-6f81-440e-a9f5-d2a4bf115e52</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContactUsConstants.TemplateIdString, Cachable=false)] 
	public partial class ContactUs  : GlassBase, IContactUs 
	{
	   
		
				/// <summary>
				/// The Abstract field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: fdd379b2-7075-40ac-abf1-e54fdb9ae183</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContactUsConstants.AbstractFieldName)]
				public virtual string Abstract  {get; set;}
					
		
				/// <summary>
				/// The Email-Id field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: a10929f6-9134-4690-8dfd-f1707a40dfa9</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContactUsConstants.Email_IdFieldName)]
				public virtual Link Email_Id  {get; set;}
					
		
				/// <summary>
				/// The Mobile No field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8ad34cd6-a8bf-487c-add7-fd8931fb442c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContactUsConstants.Mobile_NoFieldName)]
				public virtual string Mobile_No  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a3cf7dc4-6cf5-4861-81cf-1c288d262fa5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContactUsConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// INavigation Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Navigation</para>	
	/// <para>ID: 4be2d4ee-b319-46c3-a2ab-4c9da46179a7</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigationConstants.TemplateIdString, Cachable=false)]
	public partial interface INavigation : IGlassBase 
	{
			
					/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: ecb398df-41f0-4353-aed7-973bfcce7a05</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(INavigationConstants.LinkFieldName)]
					Link Link  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 6b1be471-2e8b-485e-8f10-84d709e101a3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(INavigationConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class INavigationConstants{

			public const string TemplateIdString = "4be2d4ee-b319-46c3-a2ab-4c9da46179a7";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Navigation";

		
			
			public static readonly ID LinkFieldId = new ID("ecb398df-41f0-4353-aed7-973bfcce7a05");
			public const string LinkFieldName = "Link";
			
		
			
			public static readonly ID TitleFieldId = new ID("6b1be471-2e8b-485e-8f10-84d709e101a3");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Navigation
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Navigation</para>	
	/// <para>ID: 4be2d4ee-b319-46c3-a2ab-4c9da46179a7</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigationConstants.TemplateIdString, Cachable=false)] 
	public partial class Navigation  : GlassBase, INavigation 
	{
	   
		
				/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: ecb398df-41f0-4353-aed7-973bfcce7a05</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigationConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 6b1be471-2e8b-485e-8f10-84d709e101a3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigationConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IMenu Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Menu</para>	
	/// <para>ID: 5afe81a3-614b-415b-ae95-7a18c162c7ed</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuConstants.TemplateIdString, Cachable=false)]
	public partial interface IMenu : IGlassBase 
	{
			
					/// <summary>
					/// The Menu Content field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: d28ffab8-c688-4ec7-a2f6-2b5b488038b4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMenuConstants.Menu_ContentFieldName)]
					string Menu_Content  {get; set;}
			
			
					/// <summary>
					/// The Menu Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 412e50a7-36ac-4866-b3b3-8d34207737b6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMenuConstants.Menu_ImageFieldName)]
					Image Menu_Image  {get; set;}
			
			
					/// <summary>
					/// The Menu Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 126a4b27-9601-4e0a-914d-da84bb4a32e4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMenuConstants.Menu_NameFieldName)]
					string Menu_Name  {get; set;}
			
			
					/// <summary>
					/// The Menu Time field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b00c8184-0df6-4b81-aaf9-95b20a24e328</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMenuConstants.Menu_TimeFieldName)]
					string Menu_Time  {get; set;}
			
			
					/// <summary>
					/// The Price field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 601e1873-04c4-4b26-8b15-4db99a4a442a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMenuConstants.PriceFieldName)]
					string Price  {get; set;}
			
			
	}


	public static partial class IMenuConstants{

			public const string TemplateIdString = "5afe81a3-614b-415b-ae95-7a18c162c7ed";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Menu";

		
			
			public static readonly ID Menu_ContentFieldId = new ID("d28ffab8-c688-4ec7-a2f6-2b5b488038b4");
			public const string Menu_ContentFieldName = "Menu Content";
			
		
			
			public static readonly ID Menu_ImageFieldId = new ID("412e50a7-36ac-4866-b3b3-8d34207737b6");
			public const string Menu_ImageFieldName = "Menu Image";
			
		
			
			public static readonly ID Menu_NameFieldId = new ID("126a4b27-9601-4e0a-914d-da84bb4a32e4");
			public const string Menu_NameFieldName = "Menu Name";
			
		
			
			public static readonly ID Menu_TimeFieldId = new ID("b00c8184-0df6-4b81-aaf9-95b20a24e328");
			public const string Menu_TimeFieldName = "Menu Time";
			
		
			
			public static readonly ID PriceFieldId = new ID("601e1873-04c4-4b26-8b15-4db99a4a442a");
			public const string PriceFieldName = "Price";
			
			

	}

	
	/// <summary>
	/// Menu
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Menu</para>	
	/// <para>ID: 5afe81a3-614b-415b-ae95-7a18c162c7ed</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuConstants.TemplateIdString, Cachable=false)] 
	public partial class Menu  : GlassBase, IMenu 
	{
	   
		
				/// <summary>
				/// The Menu Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: d28ffab8-c688-4ec7-a2f6-2b5b488038b4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMenuConstants.Menu_ContentFieldName)]
				public virtual string Menu_Content  {get; set;}
					
		
				/// <summary>
				/// The Menu Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 412e50a7-36ac-4866-b3b3-8d34207737b6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMenuConstants.Menu_ImageFieldName)]
				public virtual Image Menu_Image  {get; set;}
					
		
				/// <summary>
				/// The Menu Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 126a4b27-9601-4e0a-914d-da84bb4a32e4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMenuConstants.Menu_NameFieldName)]
				public virtual string Menu_Name  {get; set;}
					
		
				/// <summary>
				/// The Menu Time field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b00c8184-0df6-4b81-aaf9-95b20a24e328</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMenuConstants.Menu_TimeFieldName)]
				public virtual string Menu_Time  {get; set;}
					
		
				/// <summary>
				/// The Price field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 601e1873-04c4-4b26-8b15-4db99a4a442a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMenuConstants.PriceFieldName)]
				public virtual string Price  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IData_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Data Folder</para>	
	/// <para>ID: 6ce0278f-8351-4416-a472-544a50ece3d2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IData_FolderConstants.TemplateIdString, Cachable=false)]
	public partial interface IData_Folder : IGlassBase 
	{
			
	}


	public static partial class IData_FolderConstants{

			public const string TemplateIdString = "6ce0278f-8351-4416-a472-544a50ece3d2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Data Folder";

			

	}

	
	/// <summary>
	/// Data_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Data Folder</para>	
	/// <para>ID: 6ce0278f-8351-4416-a472-544a50ece3d2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IData_FolderConstants.TemplateIdString, Cachable=false)] 
	public partial class Data_Folder  : GlassBase, IData_Folder 
	{
	   
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IClientImageComponent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/ClientImageComponent</para>	
	/// <para>ID: 776b6643-f965-4d84-97e4-817e18f5e481</para>	
	/// </summary>
	[SitecoreType(TemplateId=IClientImageComponentConstants.TemplateIdString, Cachable=false)]
	public partial interface IClientImageComponent : IGlassBase 
	{
			
					/// <summary>
					/// The Our Clients field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: ee617bed-5b04-4a5c-8305-7fda7f90ea0e</para>
					/// <para>Custom Data: generic=Client</para>
					/// </summary>
					[SitecoreField(IClientImageComponentConstants.Our_ClientsFieldName)]
					IEnumerable<Client> Our_Clients  {get; set;}
			
			
	}


	public static partial class IClientImageComponentConstants{

			public const string TemplateIdString = "776b6643-f965-4d84-97e4-817e18f5e481";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "ClientImageComponent";

		
			
			public static readonly ID Our_ClientsFieldId = new ID("ee617bed-5b04-4a5c-8305-7fda7f90ea0e");
			public const string Our_ClientsFieldName = "Our Clients";
			
			

	}

	
	/// <summary>
	/// ClientImageComponent
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/ClientImageComponent</para>	
	/// <para>ID: 776b6643-f965-4d84-97e4-817e18f5e481</para>	
	/// </summary>
	[SitecoreType(TemplateId=IClientImageComponentConstants.TemplateIdString, Cachable=false)] 
	public partial class ClientImageComponent  : GlassBase, IClientImageComponent 
	{
	   
		
				/// <summary>
				/// The Our Clients field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: ee617bed-5b04-4a5c-8305-7fda7f90ea0e</para>
				/// <para>Custom Data: generic=Client</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IClientImageComponentConstants.Our_ClientsFieldName)]
				public virtual IEnumerable<Client> Our_Clients  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IClient Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Client</para>	
	/// <para>ID: 7ae37858-f294-4ea2-9ee5-428377011f57</para>	
	/// </summary>
	[SitecoreType(TemplateId=IClientConstants.TemplateIdString, Cachable=false)]
	public partial interface IClient : IGlassBase 
	{
			
					/// <summary>
					/// The Client Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 897ee17c-c11e-4046-8f28-a96103f201a9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IClientConstants.Client_ImageFieldName)]
					Image Client_Image  {get; set;}
			
			
	}


	public static partial class IClientConstants{

			public const string TemplateIdString = "7ae37858-f294-4ea2-9ee5-428377011f57";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Client";

		
			
			public static readonly ID Client_ImageFieldId = new ID("897ee17c-c11e-4046-8f28-a96103f201a9");
			public const string Client_ImageFieldName = "Client Image";
			
			

	}

	
	/// <summary>
	/// Client
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Client</para>	
	/// <para>ID: 7ae37858-f294-4ea2-9ee5-428377011f57</para>	
	/// </summary>
	[SitecoreType(TemplateId=IClientConstants.TemplateIdString, Cachable=false)] 
	public partial class Client  : GlassBase, IClient 
	{
	   
		
				/// <summary>
				/// The Client Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 897ee17c-c11e-4046-8f28-a96103f201a9</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IClientConstants.Client_ImageFieldName)]
				public virtual Image Client_Image  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IOur_Menu Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Our Menu</para>	
	/// <para>ID: 7bfe3344-ec8b-4e2d-be22-d4bf923955db</para>	
	/// </summary>
	[SitecoreType(TemplateId=IOur_MenuConstants.TemplateIdString, Cachable=false)]
	public partial interface IOur_Menu : IGlassBase , global::PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi.IBase_Page
	{
			
					/// <summary>
					/// The Sub Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: c603d0b5-366b-4a04-9a90-7421e1bf6a6a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IOur_MenuConstants.Sub_TitleFieldName)]
					string Sub_Title  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 7eb64d8d-4016-40b7-a469-a3161d8e045d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IOur_MenuConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IOur_MenuConstants{

			public const string TemplateIdString = "7bfe3344-ec8b-4e2d-be22-d4bf923955db";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Our Menu";

		
			
			public static readonly ID Sub_TitleFieldId = new ID("c603d0b5-366b-4a04-9a90-7421e1bf6a6a");
			public const string Sub_TitleFieldName = "Sub Title";
			
		
			
			public static readonly ID TitleFieldId = new ID("7eb64d8d-4016-40b7-a469-a3161d8e045d");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Our_Menu
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Our Menu</para>	
	/// <para>ID: 7bfe3344-ec8b-4e2d-be22-d4bf923955db</para>	
	/// </summary>
	[SitecoreType(TemplateId=IOur_MenuConstants.TemplateIdString, Cachable=false)] 
	public partial class Our_Menu  : GlassBase, IOur_Menu 
	{
	   
		
				/// <summary>
				/// The Sub Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: c603d0b5-366b-4a04-9a90-7421e1bf6a6a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IOur_MenuConstants.Sub_TitleFieldName)]
				public virtual string Sub_Title  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 7eb64d8d-4016-40b7-a469-a3161d8e045d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IOur_MenuConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// ISiteSettings Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/SiteSettings</para>	
	/// <para>ID: 858936e0-963a-437e-a1d7-63128d9df45a</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteSettingsConstants.TemplateIdString, Cachable=false)]
	public partial interface ISiteSettings : IGlassBase 
	{
			
					/// <summary>
					/// The Copyright field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 3a3c99de-0945-4c22-b60a-e106716b1d9f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteSettingsConstants.CopyrightFieldName)]
					string Copyright  {get; set;}
			
			
					/// <summary>
					/// The HomePage Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 38b3ee2d-ec47-44ee-a7ef-8f84caf52e5f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteSettingsConstants.HomePage_LinkFieldName)]
					Link HomePage_Link  {get; set;}
			
			
					/// <summary>
					/// The HomePage Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d330c985-97c9-4e8c-877b-5b756678f8e9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteSettingsConstants.HomePage_TitleFieldName)]
					string HomePage_Title  {get; set;}
			
			
					/// <summary>
					/// The NavigationLists field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 77b29878-9986-48f3-9563-52d166dff314</para>
					/// <para>Custom Data: generic=Navigation</para>
					/// </summary>
					[SitecoreField(ISiteSettingsConstants.NavigationListsFieldName)]
					IEnumerable<Navigation> NavigationLists  {get; set;}
			
			
	}


	public static partial class ISiteSettingsConstants{

			public const string TemplateIdString = "858936e0-963a-437e-a1d7-63128d9df45a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteSettings";

		
			
			public static readonly ID CopyrightFieldId = new ID("3a3c99de-0945-4c22-b60a-e106716b1d9f");
			public const string CopyrightFieldName = "Copyright";
			
		
			
			public static readonly ID HomePage_LinkFieldId = new ID("38b3ee2d-ec47-44ee-a7ef-8f84caf52e5f");
			public const string HomePage_LinkFieldName = "HomePage Link";
			
		
			
			public static readonly ID HomePage_TitleFieldId = new ID("d330c985-97c9-4e8c-877b-5b756678f8e9");
			public const string HomePage_TitleFieldName = "HomePage Title";
			
		
			
			public static readonly ID NavigationListsFieldId = new ID("77b29878-9986-48f3-9563-52d166dff314");
			public const string NavigationListsFieldName = "NavigationLists";
			
			

	}

	
	/// <summary>
	/// SiteSettings
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/SiteSettings</para>	
	/// <para>ID: 858936e0-963a-437e-a1d7-63128d9df45a</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteSettingsConstants.TemplateIdString, Cachable=false)] 
	public partial class SiteSettings  : GlassBase, ISiteSettings 
	{
	   
		
				/// <summary>
				/// The Copyright field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3a3c99de-0945-4c22-b60a-e106716b1d9f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSettingsConstants.CopyrightFieldName)]
				public virtual string Copyright  {get; set;}
					
		
				/// <summary>
				/// The HomePage Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 38b3ee2d-ec47-44ee-a7ef-8f84caf52e5f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSettingsConstants.HomePage_LinkFieldName)]
				public virtual Link HomePage_Link  {get; set;}
					
		
				/// <summary>
				/// The HomePage Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d330c985-97c9-4e8c-877b-5b756678f8e9</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSettingsConstants.HomePage_TitleFieldName)]
				public virtual string HomePage_Title  {get; set;}
					
		
				/// <summary>
				/// The NavigationLists field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: 77b29878-9986-48f3-9563-52d166dff314</para>
				/// <para>Custom Data: generic=Navigation</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSettingsConstants.NavigationListsFieldName)]
				public virtual IEnumerable<Navigation> NavigationLists  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IMenuItemListComponent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/MenuItemListComponent</para>	
	/// <para>ID: 88f5b7e1-796a-41e2-8d15-4b5666d7e751</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuItemListComponentConstants.TemplateIdString, Cachable=false)]
	public partial interface IMenuItemListComponent : IGlassBase 
	{
			
					/// <summary>
					/// The Our Menus field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 0a59f065-a839-41d8-9da9-278d6de1cf0f</para>
					/// <para>Custom Data: generic=Menu</para>
					/// </summary>
					[SitecoreField(IMenuItemListComponentConstants.Our_MenusFieldName)]
					IEnumerable<Menu> Our_Menus  {get; set;}
			
			
	}


	public static partial class IMenuItemListComponentConstants{

			public const string TemplateIdString = "88f5b7e1-796a-41e2-8d15-4b5666d7e751";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "MenuItemListComponent";

		
			
			public static readonly ID Our_MenusFieldId = new ID("0a59f065-a839-41d8-9da9-278d6de1cf0f");
			public const string Our_MenusFieldName = "Our Menus";
			
			

	}

	
	/// <summary>
	/// MenuItemListComponent
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/MenuItemListComponent</para>	
	/// <para>ID: 88f5b7e1-796a-41e2-8d15-4b5666d7e751</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuItemListComponentConstants.TemplateIdString, Cachable=false)] 
	public partial class MenuItemListComponent  : GlassBase, IMenuItemListComponent 
	{
	   
		
				/// <summary>
				/// The Our Menus field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: 0a59f065-a839-41d8-9da9-278d6de1cf0f</para>
				/// <para>Custom Data: generic=Menu</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMenuItemListComponentConstants.Our_MenusFieldName)]
				public virtual IEnumerable<Menu> Our_Menus  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IAboutUs Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/AboutUs</para>	
	/// <para>ID: 92bf9bed-9e20-4e28-8efc-8a723c381a11</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAboutUsConstants.TemplateIdString, Cachable=false)]
	public partial interface IAboutUs : IGlassBase , global::PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi.IBase_Page
	{
			
					/// <summary>
					/// The Body field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: c7bd6a9f-d1b4-4935-9190-b5f8a6775629</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAboutUsConstants.BodyFieldName)]
					string Body  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 3ba63f51-f49e-4b03-8514-f9bab3927c63</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAboutUsConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IAboutUsConstants{

			public const string TemplateIdString = "92bf9bed-9e20-4e28-8efc-8a723c381a11";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "AboutUs";

		
			
			public static readonly ID BodyFieldId = new ID("c7bd6a9f-d1b4-4935-9190-b5f8a6775629");
			public const string BodyFieldName = "Body";
			
		
			
			public static readonly ID TitleFieldId = new ID("3ba63f51-f49e-4b03-8514-f9bab3927c63");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// AboutUs
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/AboutUs</para>	
	/// <para>ID: 92bf9bed-9e20-4e28-8efc-8a723c381a11</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAboutUsConstants.TemplateIdString, Cachable=false)] 
	public partial class AboutUs  : GlassBase, IAboutUs 
	{
	   
		
				/// <summary>
				/// The Body field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c7bd6a9f-d1b4-4935-9190-b5f8a6775629</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAboutUsConstants.BodyFieldName)]
				public virtual string Body  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3ba63f51-f49e-4b03-8514-f9bab3927c63</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAboutUsConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IBase_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Base Page</para>	
	/// <para>ID: cd731466-f084-4c70-8fef-80d6d85c2a18</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_PageConstants.TemplateIdString, Cachable=false)]
	public partial interface IBase_Page : IGlassBase 
	{
			
	}


	public static partial class IBase_PageConstants{

			public const string TemplateIdString = "cd731466-f084-4c70-8fef-80d6d85c2a18";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base Page";

			

	}

	
	/// <summary>
	/// Base_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Base Page</para>	
	/// <para>ID: cd731466-f084-4c70-8fef-80d6d85c2a18</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_PageConstants.TemplateIdString, Cachable=false)] 
	public partial class Base_Page  : GlassBase, IBase_Page 
	{
	   
			
	}

}
namespace PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi
{


 	/// <summary>
	/// IOur_Clients Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Our Clients</para>	
	/// <para>ID: f7c0103b-0bf5-4c76-896d-c34eaf6ab639</para>	
	/// </summary>
	[SitecoreType(TemplateId=IOur_ClientsConstants.TemplateIdString, Cachable=false)]
	public partial interface IOur_Clients : IGlassBase , global::PurePunjabi.Models.sitecore.templates.User_Defined.Pure_Punjabi.IBase_Page
	{
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: b8df54f7-c286-4aa8-b26e-ebd84eb8fa2b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IOur_ClientsConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The TItle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: caf36370-a92a-4ba8-8b80-95ee2294c4be</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IOur_ClientsConstants.TItleFieldName)]
					string TItle  {get; set;}
			
			
	}


	public static partial class IOur_ClientsConstants{

			public const string TemplateIdString = "f7c0103b-0bf5-4c76-896d-c34eaf6ab639";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Our Clients";

		
			
			public static readonly ID DescriptionFieldId = new ID("b8df54f7-c286-4aa8-b26e-ebd84eb8fa2b");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TItleFieldId = new ID("caf36370-a92a-4ba8-8b80-95ee2294c4be");
			public const string TItleFieldName = "TItle";
			
			

	}

	
	/// <summary>
	/// Our_Clients
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Pure Punjabi/Our Clients</para>	
	/// <para>ID: f7c0103b-0bf5-4c76-896d-c34eaf6ab639</para>	
	/// </summary>
	[SitecoreType(TemplateId=IOur_ClientsConstants.TemplateIdString, Cachable=false)] 
	public partial class Our_Clients  : GlassBase, IOur_Clients 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: b8df54f7-c286-4aa8-b26e-ebd84eb8fa2b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IOur_ClientsConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The TItle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: caf36370-a92a-4ba8-8b80-95ee2294c4be</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IOur_ClientsConstants.TItleFieldName)]
				public virtual string TItle  {get; set;}
					
			
	}

}
